version: '2'

services:
    reverseproxy:
        build: .
        hostname: proxy
        depends_on:
          - web1
        image: reverseproxy
        ports:
            - 8080:8080
        networks:
                - app_network
    web1:
        build: web/
        hostname: web1
        image: nginx-web1
        networks:
                - app_network
networks:
        app_network:
                external: true
